added two code examples: add_local_campaign.rb and handle_rate_exceeded_error.rb
googleads/google-ads-ruby pull request #250
Opened 2020-11-23 08:13 UTC by xflesym

examples/advanced_operations/add_local_campaign.rb
	examples/error_handling/handle_rate_exceeded_error.rb

2020-11-24 07:42 UTC, fiboknacky requested changes

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "Created campaign budget with resource name: #{budget_resource_name}"
Add single quote around a string (budget resource name)

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "Created Local campaign with resource name: #{campaign_resource_name}"
Ditto

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "Created ad group with resource name: #{ad_group_resource_name}"
Ditto

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +    "#{response.results.first.resource_name}"
Ditto

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "A new image asset has been added with resource name: " \
Ditto

2020-11-24 07:42 UTC, fiboknacky commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "A new YouTube video asset has been added with resource name: " \
Ditto

2020-11-24 07:57 UTC, xflesym commented on examples/advanced_operations/add_local_campaign.rb
> +  puts "Created campaign budget with resource name: #{budget_resource_name}"
Done.

2020-11-24 10:35 UTC, fiboknacky approved these changes

2020-11-30 14:17 UTC, mcloonan requested changes

2020-11-30 14:17 UTC, mcloonan commented on examples/error_handling/handle_rate_exceeded_error.rb
> +  for i in 0..NUM_REQUESTS-1
NUMREQUESTS.times do |i|

2020-11-30 14:17 UTC, mcloonan commented on examples/error_handling/handle_rate_exceeded_error.rb
> +  for i in 0..NUM_KEYWORDS-1
Same here.

2020-12-01 06:17 UTC, xflesym commented on examples/error_handling/handle_rate_exceeded_error.rb
> +  for i in 0..NUM_REQUESTS-1
Done.

2020-12-01 06:18 UTC, xflesym commented on examples/error_handling/handle_rate_exceeded_error.rb
> +  for i in 0..NUM_KEYWORDS-1
Done.

2020-12-01 13:46 UTC, mcloonan approved these changes

2020-12-01 13:46 UTC, merged