Various example renaming fixes.
googleads/google-ads-ruby pull request #364
Opened 2021-12-10 17:12 UTC by mcloonan

Change-Id: I348cc2d102ffba2b835820ccdf12591c21176455

2021-12-10 18:01 UTC, abraham approved these changes

2021-12-13 03:06 UTC, wfansh requested changes

2021-12-13 03:06 UTC, wfansh commented on examples/extensions/add_business_profile_location_extensions.rb
> +  business_profile_email_address,
this should be "business_profile_email" without "_address" suffix. Please see
https://github.com/googleads/google-ads-php/blob/main/examples/Extensions/AddBusinessProfileLocationExtensions.php#L53

2021-12-13 09:15 UTC, wfansh commented on examples/extensions/add_business_profile_location_extensions.rb
> +  business_profile_email_address,
Please update before merge.

2021-12-13 09:15 UTC, wfansh approved these changes

2021-12-16 14:48 UTC, AnashOommen approved these changes

2021-12-20 19:11 UTC, merged